In [3]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3]])
print(a)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]


In [2]:
b = a
b.reshape(2,6)


array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2, 3]])

In [6]:
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3])

In [7]:
for x in a.flat:
    print(x)

1
2
3
4
5
6
7
8
9
1
2
3


In [10]:
print(a.flat[2])

3


In [11]:
b =np.array([
    [3,4,5,6],
    [2,4,7,9],
    [1,5,7,9]
])

In [20]:
c = np. concatenate((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]
 [3 4 5 6]
 [2 4 7 9]
 [1 5 7 9]]


In [15]:
print(b)

[[3 4 5 6]
 [2 4 7 9]
 [1 5 7 9]]


In [21]:
c2 = np.stack((a,b))

In [22]:
print(c2)

[[[1 2 3 4]
  [5 6 7 8]
  [9 1 2 3]]

 [[3 4 5 6]
  [2 4 7 9]
  [1 5 7 9]]]


In [26]:
print(c.shape)
print(c2.shape)

(6, 4)
(2, 3, 4)


In [30]:
print(np.split(c,3))

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[9, 1, 2, 3],
       [3, 4, 5, 6]]), array([[2, 4, 7, 9],
       [1, 5, 7, 9]])]


In [34]:
print(np.hsplit(c,2)) #horizontal

[array([[1, 2],
       [5, 6],
       [9, 1],
       [3, 4],
       [2, 4],
       [1, 5]]), array([[3, 4],
       [7, 8],
       [2, 3],
       [5, 6],
       [7, 9],
       [7, 9]])]


In [37]:
print(np.append(a,b,axis =0)) #append horizontal

[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]
 [3 4 5 6]
 [2 4 7 9]
 [1 5 7 9]]


In [38]:
print(np.append(a,b,axis =1)) #append vertically

[[1 2 3 4 3 4 5 6]
 [5 6 7 8 2 4 7 9]
 [9 1 2 3 1 5 7 9]]


In [41]:
print(np.insert(a,1,b,axis=0)) #1 is index of row

[[1 2 3 4]
 [3 4 5 6]
 [2 4 7 9]
 [1 5 7 9]
 [5 6 7 8]
 [9 1 2 3]]


In [51]:
print(np.insert(a,2,[[0,0,0],[0,1,0]],axis=1)) #1 is index of column it's not woking

[[1 2 0 0 3 4]
 [5 6 0 1 7 8]
 [9 1 0 0 2 3]]


[[3 4 5 6]
 [2 4 7 9]
 [1 5 7 9]]
